#ifndef GRAPHICS_INTERNAL_PLATFORM_GL_INCLUDES_HPP
#define GRAPHICS_INTERNAL_PLATFORM_GL_INCLUDES_HPP

#define GLFW_INCLUDE_NONE
#include <GL/gl3w.h>
#include <GLFW/glfw3.h>

#endif // GRAPHICS_INTERNAL_PLATFORM_GL_INCLUDES_HPP