name: clang-format

on:
  pull_request:
    branches: [ "main" ]

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          
      - name: Install clang-format
        run: |
          pip install clang-format==22.1.5
          
      - run: clang-format --version

      - name: Apply clang-format
        run: |
          git ls-files '*.cpp' '*.hpp' '*.h' | xargs clang-format -i

      - name: Commit changes
        run: |
          if ! git diff --quiet; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git commit -am "Apply clang-format"
            git push
          fi
