name: clang-format

on:
  pull_request:
    branches: [ "main" ]

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Add the Official LLVM APT repository
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 22

      - name: Install clang-tidy-22
        run: sudo apt-get install -y clang-format-22

      - name: Verify Installation
        run: clang-format-22 --version

      - name: Apply clang-format
        run: |
          git ls-files '*.cpp' '*.hpp' '*.h' | xargs clang-format-22 -i

      - name: Commit changes
        run: |
          if ! git diff --quiet; then
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git commit -am "Apply clang-format"
            git push
          fi
